### ISSUE TITLE
URLencoded  thumbnails in image search API

### ISSUE THREAD

**Issue by trueauracoral** [hnhx/librex#34]
So when looking at the API on this example url: https://search.davidovski.xyz/api.php?q=pop%20os%20my%20dream%20os&type=1. The json output gives values like this one:

`https%3A%2F%2Fs2.qwant.com%2Fthumbr%2F474x165%2F5%2Fe%2F51d63491bae5988d93be20d8ffdd7ab9da8b564fe4839f75a979eb9c9e84cb%2Fth.jpg%3Fu%3Dhttps%253A%252F%252Ftse4.mm.bing.net%252Fth%253Fid%253DOIP.vZWeI6ZB7gUrNYJCpGHbuwHaCl%2526pid%253DApi%26q%3D0%26b%3D1%26p%3D0%26a%3D0`

It should look like:

`https://s2.qwant.com/thumbr/474x165/5/e/51d63491bae5988d93be20d8ffdd7ab9da8b564fe4839f75a979eb9c9e84cb/th.jpg?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.vZWeI6ZB7gUrNYJCpGHbuwHaCl%26pid%3DApi&q=0&b=1&p=0&a=0`

Could some url decoding be done in the API?

**Comment by hnhx** [comment]
fixed it

**Comment by trueauracoral** [comment]
https://search.davidovski.xyz/api.php?q=linux&type=1

I still see that the url's don't look right.
